/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze/{owner}/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        /**
         * Analyze repository test specifications
         * @description Triggers or retrieves analysis for a GitHub repository.
         *     - Returns completed analysis if available
         *     - Queues new analysis if not found
         *     - Returns current status if analysis is in progress
         *
         */
        get: operations["analyzeRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/{owner}/{repo}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        /**
         * Get analysis status
         * @description Check the current status of repository analysis
         */
        get: operations["getAnalysisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisResponse: components["schemas"]["CompletedResponse"] | components["schemas"]["AnalyzingResponse"] | components["schemas"]["QueuedResponse"] | components["schemas"]["FailedResponse"];
        CompletedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
            data: components["schemas"]["AnalysisResult"];
        };
        AnalyzingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "analyzing";
        };
        QueuedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "queued";
        };
        FailedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            /** @description Error message describing the failure */
            error: string;
        };
        AnalysisResult: {
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of analysis completion
             * @example 2024-01-15T10:30:00Z
             */
            analyzedAt: string;
            /**
             * @description Git commit SHA that was analyzed
             * @example abc123def456
             */
            commitSha: string;
            /**
             * @description Repository owner
             * @example facebook
             */
            owner: string;
            /**
             * @description Repository name
             * @example react
             */
            repo: string;
            suites: components["schemas"]["TestSuite"][];
            summary: components["schemas"]["Summary"];
        };
        TestSuite: {
            /**
             * @description Path to the test file relative to repository root
             * @example src/__tests__/App.test.tsx
             */
            filePath: string;
            framework: components["schemas"]["Framework"];
            tests: components["schemas"]["TestCase"][];
        };
        TestCase: {
            /** @description Path to the test file */
            filePath: string;
            framework: components["schemas"]["Framework"];
            /** @description Line number where the test is defined */
            line: number;
            /** @description Test modifier (e.g., only, skip) */
            modifier?: string;
            /** @description Test case name */
            name: string;
            status: components["schemas"]["TestStatus"];
        };
        /**
         * @description Test status indicator:
         *     - active: Normal test that will run
         *     - focused: Test marked to run exclusively (e.g., it.only)
         *     - skipped: Test marked to be skipped (e.g., it.skip)
         *     - todo: Placeholder test to be implemented
         *     - xfail: Expected to fail (pytest xfail)
         *
         * @enum {string}
         */
        TestStatus: "active" | "focused" | "skipped" | "todo" | "xfail";
        /**
         * @description Testing framework identifier
         * @example vitest
         */
        Framework: string;
        Summary: {
            /** @description Number of active tests */
            active: number;
            /** @description Number of focused tests */
            focused: number;
            frameworks: components["schemas"]["FrameworkSummary"][];
            /** @description Number of skipped tests */
            skipped: number;
            /** @description Number of todo tests */
            todo: number;
            /** @description Total number of tests */
            total: number;
            /** @description Number of xfail tests */
            xfail: number;
        };
        FrameworkSummary: {
            active: number;
            focused: number;
            framework: components["schemas"]["Framework"];
            skipped: number;
            todo: number;
            total: number;
            xfail: number;
        };
        ProblemDetail: {
            /**
             * Format: uri
             * @description URI identifying the problem type
             * @default about:blank
             */
            type: string;
            /** @description Human-readable summary */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Human-readable explanation specific to this occurrence */
            detail: string;
            /** @description URI reference identifying the specific occurrence */
            instance?: string;
            rateLimit?: components["schemas"]["RateLimitInfo"];
        };
        RateLimitInfo: {
            /** @description Maximum requests allowed per time window */
            limit: number;
            /** @description Remaining requests in current window */
            remaining: number;
            /**
             * Format: int64
             * @description Unix timestamp when the rate limit resets
             */
            resetAt: number;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /**
         * @description GitHub repository owner (user or organization)
         * @example facebook
         */
        Owner: string;
        /**
         * @description GitHub repository name
         * @example react
         */
        Repo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyzeRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedResponse"];
                };
            };
            /** @description Analysis accepted and processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"] | components["schemas"]["AnalyzingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getAnalysisStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description GitHub repository owner (user or organization)
                 * @example facebook
                 */
                owner: components["parameters"]["Owner"];
                /**
                 * @description GitHub repository name
                 * @example react
                 */
                repo: components["parameters"]["Repo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis status retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
