export const CONVERSION_LANGUAGES = [
  "ar",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "fi",
  "fr",
  "hi",
  "id",
  "it",
  "ja",
  "ko",
  "nl",
  "pl",
  "pt",
  "ru",
  "sv",
  "th",
  "tr",
  "uk",
  "vi",
  "zh",
] as const;

export type ConversionLanguage = (typeof CONVERSION_LANGUAGES)[number];

export const DEFAULT_CONVERSION_LANGUAGE: ConversionLanguage = "en";

export const LANGUAGE_LABELS: Record<ConversionLanguage, string> = {
  ar: "العربية (Arabic)",
  cs: "Čeština (Czech)",
  da: "Dansk (Danish)",
  de: "Deutsch (German)",
  el: "Ελληνικά (Greek)",
  en: "English",
  es: "Español (Spanish)",
  fi: "Suomi (Finnish)",
  fr: "Français (French)",
  hi: "हिन्दी (Hindi)",
  id: "Bahasa Indonesia",
  it: "Italiano (Italian)",
  ja: "日本語 (Japanese)",
  ko: "한국어 (Korean)",
  nl: "Nederlands (Dutch)",
  pl: "Polski (Polish)",
  pt: "Português (Portuguese)",
  ru: "Русский (Russian)",
  sv: "Svenska (Swedish)",
  th: "ไทย (Thai)",
  tr: "Türkçe (Turkish)",
  uk: "Українська (Ukrainian)",
  vi: "Tiếng Việt (Vietnamese)",
  zh: "中文 (Chinese)",
};
