// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TestStatus.
const (
	Active  TestStatus = "active"
	Focused TestStatus = "focused"
	Skipped TestStatus = "skipped"
	Todo    TestStatus = "todo"
	Xfail   TestStatus = "xfail"
)

// AnalysisResponse defines model for AnalysisResponse.
type AnalysisResponse struct {
	union json.RawMessage
}

// AnalysisResult defines model for AnalysisResult.
type AnalysisResult struct {
	// AnalyzedAt ISO 8601 timestamp of analysis completion
	AnalyzedAt time.Time `json:"analyzedAt"`

	// CommitSHA Git commit SHA that was analyzed
	CommitSHA string `json:"commitSha"`

	// Owner Repository owner
	Owner string `json:"owner"`

	// Repo Repository name
	Repo    string      `json:"repo"`
	Suites  []TestSuite `json:"suites"`
	Summary Summary     `json:"summary"`
}

// AnalyzingResponse defines model for AnalyzingResponse.
type AnalyzingResponse struct {
	Status string `json:"status"`
}

// CompletedResponse defines model for CompletedResponse.
type CompletedResponse struct {
	Data   AnalysisResult `json:"data"`
	Status string         `json:"status"`
}

// FailedResponse defines model for FailedResponse.
type FailedResponse struct {
	// Error Error message describing the failure
	Error  string `json:"error"`
	Status string `json:"status"`
}

// Framework Testing framework identifier
type Framework = string

// FrameworkSummary defines model for FrameworkSummary.
type FrameworkSummary struct {
	Active  int `json:"active"`
	Focused int `json:"focused"`

	// Framework Testing framework identifier
	Framework Framework `json:"framework"`
	Skipped   int       `json:"skipped"`
	Todo      int       `json:"todo"`
	Total     int       `json:"total"`
	Xfail     int       `json:"xfail"`
}

// ProblemDetail defines model for ProblemDetail.
type ProblemDetail struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail string `json:"detail"`

	// Instance URI reference identifying the specific occurrence
	Instance  *string        `json:"instance,omitempty"`
	RateLimit *RateLimitInfo `json:"rateLimit,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Human-readable summary
	Title string `json:"title"`

	// Type URI identifying the problem type
	Type *string `json:"type,omitempty"`
}

// QueuedResponse defines model for QueuedResponse.
type QueuedResponse struct {
	Status string `json:"status"`
}

// RateLimitInfo defines model for RateLimitInfo.
type RateLimitInfo struct {
	// Limit Maximum requests allowed per time window
	Limit int `json:"limit"`

	// Remaining Remaining requests in current window
	Remaining int `json:"remaining"`

	// ResetAt Unix timestamp when the rate limit resets
	ResetAt int64 `json:"resetAt"`
}

// Summary defines model for Summary.
type Summary struct {
	// Active Number of active tests
	Active int `json:"active"`

	// Focused Number of focused tests
	Focused    int                `json:"focused"`
	Frameworks []FrameworkSummary `json:"frameworks"`

	// Skipped Number of skipped tests
	Skipped int `json:"skipped"`

	// Todo Number of todo tests
	Todo int `json:"todo"`

	// Total Total number of tests
	Total int `json:"total"`

	// Xfail Number of xfail tests
	Xfail int `json:"xfail"`
}

// TestCase defines model for TestCase.
type TestCase struct {
	// FilePath Path to the test file
	FilePath string `json:"filePath"`

	// Framework Testing framework identifier
	Framework Framework `json:"framework"`

	// Line Line number where the test is defined
	Line int `json:"line"`

	// Modifier Test modifier (e.g., only, skip)
	Modifier *string `json:"modifier,omitempty"`

	// Name Test case name
	Name string `json:"name"`

	// Status Test status indicator:
	// - active: Normal test that will run
	// - focused: Test marked to run exclusively (e.g., it.only)
	// - skipped: Test marked to be skipped (e.g., it.skip)
	// - todo: Placeholder test to be implemented
	// - xfail: Expected to fail (pytest xfail)
	Status TestStatus `json:"status"`
}

// TestStatus Test status indicator:
// - active: Normal test that will run
// - focused: Test marked to run exclusively (e.g., it.only)
// - skipped: Test marked to be skipped (e.g., it.skip)
// - todo: Placeholder test to be implemented
// - xfail: Expected to fail (pytest xfail)
type TestStatus string

// TestSuite defines model for TestSuite.
type TestSuite struct {
	// FilePath Path to the test file relative to repository root
	FilePath string `json:"filePath"`

	// Framework Testing framework identifier
	Framework Framework  `json:"framework"`
	Tests     []TestCase `json:"tests"`
}

// Owner defines model for Owner.
type Owner = string

// Repo defines model for Repo.
type Repo = string

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetail

// InternalError defines model for InternalError.
type InternalError = ProblemDetail

// NotFound defines model for NotFound.
type NotFound = ProblemDetail

// AsCompletedResponse returns the union data inside the AnalysisResponse as a CompletedResponse
func (t AnalysisResponse) AsCompletedResponse() (CompletedResponse, error) {
	var body CompletedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCompletedResponse overwrites any union data inside the AnalysisResponse as the provided CompletedResponse
func (t *AnalysisResponse) FromCompletedResponse(v CompletedResponse) error {
	v.Status = "completed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCompletedResponse performs a merge with any union data inside the AnalysisResponse, using the provided CompletedResponse
func (t *AnalysisResponse) MergeCompletedResponse(v CompletedResponse) error {
	v.Status = "completed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnalyzingResponse returns the union data inside the AnalysisResponse as a AnalyzingResponse
func (t AnalysisResponse) AsAnalyzingResponse() (AnalyzingResponse, error) {
	var body AnalyzingResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnalyzingResponse overwrites any union data inside the AnalysisResponse as the provided AnalyzingResponse
func (t *AnalysisResponse) FromAnalyzingResponse(v AnalyzingResponse) error {
	v.Status = "analyzing"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnalyzingResponse performs a merge with any union data inside the AnalysisResponse, using the provided AnalyzingResponse
func (t *AnalysisResponse) MergeAnalyzingResponse(v AnalyzingResponse) error {
	v.Status = "analyzing"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueuedResponse returns the union data inside the AnalysisResponse as a QueuedResponse
func (t AnalysisResponse) AsQueuedResponse() (QueuedResponse, error) {
	var body QueuedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueuedResponse overwrites any union data inside the AnalysisResponse as the provided QueuedResponse
func (t *AnalysisResponse) FromQueuedResponse(v QueuedResponse) error {
	v.Status = "queued"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueuedResponse performs a merge with any union data inside the AnalysisResponse, using the provided QueuedResponse
func (t *AnalysisResponse) MergeQueuedResponse(v QueuedResponse) error {
	v.Status = "queued"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedResponse returns the union data inside the AnalysisResponse as a FailedResponse
func (t AnalysisResponse) AsFailedResponse() (FailedResponse, error) {
	var body FailedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedResponse overwrites any union data inside the AnalysisResponse as the provided FailedResponse
func (t *AnalysisResponse) FromFailedResponse(v FailedResponse) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedResponse performs a merge with any union data inside the AnalysisResponse, using the provided FailedResponse
func (t *AnalysisResponse) MergeFailedResponse(v FailedResponse) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnalysisResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t AnalysisResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "analyzing":
		return t.AsAnalyzingResponse()
	case "completed":
		return t.AsCompletedResponse()
	case "failed":
		return t.AsFailedResponse()
	case "queued":
		return t.AsQueuedResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AnalysisResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnalysisResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
