// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForUpsertCachedConversions implements pgx.CopyFromSource.
type iteratorForUpsertCachedConversions struct {
	rows                 []UpsertCachedConversionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForUpsertCachedConversions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForUpsertCachedConversions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CacheKeyHash,
		r.rows[0].CodebaseID,
		r.rows[0].FilePath,
		r.rows[0].Framework,
		r.rows[0].SuiteHierarchy,
		r.rows[0].OriginalName,
		r.rows[0].ConvertedName,
		r.rows[0].Language,
		r.rows[0].ModelID,
	}, nil
}

func (r iteratorForUpsertCachedConversions) Err() error {
	return nil
}

func (q *Queries) UpsertCachedConversions(ctx context.Context, arg []UpsertCachedConversionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"spec_view_cache"}, []string{"cache_key_hash", "codebase_id", "file_path", "framework", "suite_hierarchy", "original_name", "converted_name", "language", "model_id"}, &iteratorForUpsertCachedConversions{rows: arg})
}
